services:
  only-while-written:
    build: .
    container_name: only-while-written
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.only-while-written.rule=Host(`only-while-written.rajuan.app`)"
      - "traefik.http.routers.only-while-written.entrypoints=websecure"
      - "traefik.http.routers.only-while-written.tls.certresolver=letsencrypt"
      - "traefik.http.services.only-while-written.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    name: traefik-public
    external: true
